# Generated by Django 5.1.5 on 2025-02-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='description',
        ),
        migrations.AddField(
            model_name='clothes',
            name='price',
            field=models.FloatField(default=250, null=True),
        ),
    ]
