# Generated by Django 5.1.5 on 2025-02-23 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_busketmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusketModel',
        ),
    ]
