# Generated by Django 5.1.5 on 2025-02-27 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_busketmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusketModel',
        ),
    ]
